apiVersion: apps/v1
kind: Deployment
metadata:
  name: gold-frontend-deployment
  labels:
    app: gold-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gold-frontend
  template:
    metadata:
      labels:
        app: gold-frontend
    spec:
      containers:
      - name: gold-frontend
        image: 049061799945.dkr.ecr.sa-east-1.amazonaws.com/shopping-site-gold:ae1e297a5b4bd2d3a52537e1f7b0d05e13619f4c
        ports:
        - containerPort: 80
