apiVersion: apps/v1
kind: Deployment
metadata:
  name: gold-frontend-deployment
  labels:
    app: gold-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gold-frontend
  template:
    metadata:
      labels:
        app: gold-frontend
    spec:
      containers:
      - name: gold-frontend
        image: 049061799945.dkr.ecr.sa-east-1.amazonaws.com/shopping-site-gold:de2b701f03a82318cc6e05f8a29763f59ae4da3e
        ports:
        - containerPort: 80
