apiVersion: apps/v1
kind: Deployment
metadata:
  name: gold-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gold
  template:
    metadata:
      labels:
        app: gold
    spec:
      containers:
        - name: gold
          image: 049061799945.dkr.ecr.sa-east-1.amazonaws.com/shopping-site-gold:2a1802d5d6a39a4d00836aa9c6d8d218928eb1f9
          ports:
            - containerPort: 80
