apiVersion: apps/v1
kind: Deployment
metadata:
  name: gold-frontend-deployment
  labels:
    app: gold-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gold-frontend
  template:
    metadata:
      labels:
        app: gold-frontend
    spec:
      containers:
      - name: gold-frontend
        image: 049061799945.dkr.ecr.sa-east-1.amazonaws.com/shopping-site-gold:bc795ab3b12d330a6b6fe71a66eaab0fa65f73e3
        ports:
        - containerPort: 80
