apiVersion: apps/v1
kind: Deployment
metadata:
  name: gold-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gold
  template:
    metadata:
      labels:
        app: gold
    spec:
      containers:
        - name: gold
          image: <AWS_ECR_REGISTRY>/gold:latest
          ports:
            - containerPort: 80
