apiVersion: apps/v1
kind: Deployment
metadata:
  name: gold-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gold
  template:
    metadata:
      labels:
        app: gold
    spec:
      containers:
        - name: gold
          image: 049061799945.dkr.ecr.sa-east-1.amazonaws.com/shopping-site-gold:4c235faf398acab192506d76bec56b79905ca381
          ports:
            - containerPort: 80
