apiVersion: apps/v1
kind: Deployment
metadata:
  name: diamond-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diamond
  template:
    metadata:
      labels:
        app: diamond
    spec:
      containers:
        - name: diamond
          image: 049061799945.dkr.ecr.sa-east-1.amazonaws.com/shopping-site-gold:70a8705debb22526a1a8d52fa88d6d351f438a45
          ports:
            - containerPort: 80
