apiVersion: apps/v1
kind: Deployment
metadata:
  name: diamond-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diamond
  template:
    metadata:
      labels:
        app: diamond
    spec:
      containers:
        - name: diamond
          image: 049061799945.dkr.ecr.sa-east-1.amazonaws.com/shopping-site-diamond:0ffefbd7a2660acca0dfca9d47f2a0ead79bf34b
          ports:
            - containerPort: 80
