apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  defaultBackend:
    service:
      name: main-frontend-service   # your home page service
      port:
        number: 80

  rules:
    - http:
        paths:
          - path: /gold
            pathType: Prefix
            backend:
              service:
                name: gold-service
                port:
                  number: 80

          - path: /diamond
            pathType: Prefix
            backend:
              service:
                name: diamond-service
                port:
                  number: 80

          - path: /pearl
            pathType: Prefix
            backend:
              service:
                name: pearl-service
                port:
                  number: 80

          - path: /silver
            pathType: Prefix
            backend:
              service:
                name: silver-service
                port:
                  number: 80
