apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # MAIN
          - path: /
            pathType: Prefix
            backend:
              service:
                name: main-service
                port:
                  number: 80

          # GOLD
          - path: /gold
            pathType: Prefix
            backend:
              service:
                name: gold-service
                port:
                  number: 80

          # DIAMOND
          - path: /diamond
            pathType: Prefix
            backend:
              service:
                name: diamond-service
                port:
                  number: 80

          # PEARL
          - path: /pearl
            pathType: Prefix
            backend:
              service:
                name: pearl-service
                port:
                  number: 80

          # SILVER
          - path: /silver
            pathType: Prefix
            backend:
              service:
                name: silver-service
                port:
                  number: 80
