apiVersion: apps/v1
kind: Deployment
metadata:
  name: pearl-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pearl
  template:
    metadata:
      labels:
        app: pearl
    spec:
      containers:
        - name: pearl
          image: 049061799945.dkr.ecr.sa-east-1.amazonaws.com/shopping-site-pearl:ba76c3e27adb1efce40c6469bbd03ac041511cb0
          ports:
            - containerPort: 80
